name: CI

on:
  push:
    branches:
      - "**"

jobs:

  php84:
    name: "php 8.4"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.4"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer update --no-interaction --prefer-lowest

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

  php83:
    name: "php 8.3"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.3"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: phive install --trust-gpg-keys E82B2FB314E9906E

      - name: Install dependencies
        run: composer update --no-interaction --prefer-lowest

      - name: Chesk code style
        run: tools/php-cs-fixer fix --dry-run --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

  php82:
    name: "php 8.2"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.2"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --prefer-lowest

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

  php81:
    name: "php 8.1"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --prefer-lowest

      - name: Run static analysis
        run: vendor/bin/phpstan analyse
